name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup env for a good brew
        run: |
         rm /usr/local/bin/aws*
         rm /usr/local/bin/go

      - run: ./defaults.sh
      - run: ./install.sh
      - run: shellcheck *.sh
