name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cleanup env
        run: |
         rm /usr/local/bin/aws*
         rm /usr/local/bin/go*

      - name: Set my defaults
        run: ./defaults.sh

      - name: Install packages
        run: ./install.sh

      - name: Shellcheck
        run: shellcheck *.sh

      - name: Upgrade packages
        run: ./install.sh
